### ISSUE TITLE
ACR build is failing due to node version

### ISSUE THREAD

**Issue by ruchinmunjal** [dotnet/eShopOnContainers#1790]
This solution is being referenced in one of MS Learn paths [here](https://docs.microsoft.com/en-gb/learn/modules/microservices-aspnet-core/)

There is an issue when we run one of the instructions on [unit 6 of the module](https://docs.microsoft.com/en-gb/learn/modules/microservices-aspnet-core/6-add-coupon-service) . I'm not entirely sure if this issue belongs here or not. I have given the same feedback on the page as well. But since the feedback is not visible to everyone, I thought of sharing the details here as well. Feel free to close this issue if you think this doesn't belong here.

One of the [exercise ](https://docs.microsoft.com/en-gb/learn/modules/microservices-aspnet-core/6-add-coupon-service) is to add a new "Coupon" functionality to the solution by adding a new Coupon service after which a new  build is issued to the container registry

Upon running the below command the container build fails

`./deploy/k8s/build-to-acr.sh`

Error Details:

Error Message: 
error:0308010C:digital envelope routines::unsupported

Complete error stack:

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/web/src/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/web/src/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/web/src/node_modules/webpack/lib/NormalModule.js:449:10)
    at /web/src/node_modules/webpack/lib/NormalModule.js:481:5
    at /web/src/node_modules/webpack/lib/NormalModule.js:342:12
    at /web/src/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at iterateNormalLoaders (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /web/src/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at runSyncOrAsync (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at iterateNormalLoaders (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /web/src/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at context.callback (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /web/src/node_modules/postcss-loader/src/index.js:197:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
```

This error occurs because of a known backward incompatibility issue with node 17. More information [here ](https://github.com/webpack/webpack/issues/14532)

**Solution:**

The `docker `and `docker acr` file in WebSPA project generates the container images based on latest node version. Changing this to `node:16` fixes the issue.

_Complete command output_

```
~/clouddrive/aspnet-learn/src$ ./deploy/k8s/build-to-acr.sh

Building and publishing docker images to eshoplearn20211111192800181.azurecr.io...

Building image "coupon.api"...
> az acr build --registry eshoplearn20211111192800181 --image eshoplearn20211111192800181.azurecr.io/coupon.api:linux-latest --file src/Services/Coupon/Coupon.API/Dockerfile .
Packing source code into tar to upload...
Excluding '.gitignore' based on default ignore rules
Uploading archived source code from '/tmp/build_archive_519181c314474ee98797f70b0d9dc99f.tar.gz'...
Sending context (7.400 MiB) to registry: eshoplearn20211111192800181...
Queued a build with ID: cf3
Waiting for an agent...
2021/11/13 16:57:20 Downloading source code...
2021/11/13 16:57:21 Finished downloading source code
2021/11/13 16:57:21 Using acb_vol_96073953-0e92-49d5-8148-4fa1b0dc41bd as the home volume
2021/11/13 16:57:21 Setting up Docker configuration...
2021/11/13 16:57:22 Successfully set up Docker configuration
2021/11/13 16:57:22 Logging in to registry: eshoplearn20211111192800181.azurecr.io
2021/11/13 16:57:23 Successfully logged into eshoplearn20211111192800181.azurecr.io
2021/11/13 16:57:23 Executing step ID: build. Timeout(sec): 28800, Working directory: '', Network: ''
2021/11/13 16:57:23 Scanning for dependencies...
2021/11/13 16:57:24 Successfully scanned dependencies
2021/11/13 16:57:24 Launching container with name: build
Sending build context to Docker daemon  15.86MB
Step 1/20 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
3.1-buster-slim: Pulling from dotnet/core/aspnet
b380bbd43752: Pulling fs layer
e4f4d095d04a: Pulling fs layer
bac3a3896817: Pulling fs layer
4dd004cdf57c: Pulling fs layer
561aa5f288e6: Pulling fs layer
561aa5f288e6: Waiting
4dd004cdf57c: Waiting
bac3a3896817: Verifying Checksum
bac3a3896817: Download complete
b380bbd43752: Download complete
e4f4d095d04a: Verifying Checksum
e4f4d095d04a: Download complete
561aa5f288e6: Verifying Checksum
561aa5f288e6: Download complete
4dd004cdf57c: Verifying Checksum
4dd004cdf57c: Download complete
b380bbd43752: Pull complete
e4f4d095d04a: Pull complete
bac3a3896817: Pull complete
4dd004cdf57c: Pull complete
561aa5f288e6: Pull complete
Digest: sha256:f093d820b4bcfab7847e6c469104930f432a7dbc09265f6a987089b2d3a21009
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
 ---> 0bcae74bb1e8
Step 2/20 : WORKDIR /app
 ---> Running in 871a210b1cb6
Removing intermediate container 871a210b1cb6
 ---> 3ca948624be0
Step 3/20 : EXPOSE 80
 ---> Running in f2511e689b30
Removing intermediate container f2511e689b30
 ---> e3ce44c90191
Step 4/20 : EXPOSE 443
 ---> Running in eb4b0514e445
Removing intermediate container eb4b0514e445
 ---> f4c3d83145ed
Step 5/20 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
3.1-buster: Pulling from dotnet/core/sdk
07471e81507f: Pulling fs layer
c6cef1aa2170: Pulling fs layer
13a51f13be8e: Pulling fs layer
def39d67a1a7: Pulling fs layer
1d2fb970ebb8: Pulling fs layer
3b145355f2d0: Pulling fs layer
4c909b01ebfa: Pulling fs layer
def39d67a1a7: Waiting
1d2fb970ebb8: Waiting
3b145355f2d0: Waiting
4c909b01ebfa: Waiting
13a51f13be8e: Verifying Checksum
13a51f13be8e: Download complete
c6cef1aa2170: Verifying Checksum
c6cef1aa2170: Download complete
1d2fb970ebb8: Verifying Checksum
1d2fb970ebb8: Download complete
def39d67a1a7: Verifying Checksum
def39d67a1a7: Download complete
4c909b01ebfa: Verifying Checksum
4c909b01ebfa: Download complete
07471e81507f: Verifying Checksum
07471e81507f: Download complete
3b145355f2d0: Verifying Checksum
3b145355f2d0: Download complete
07471e81507f: Pull complete
c6cef1aa2170: Pull complete
13a51f13be8e: Pull complete
def39d67a1a7: Pull complete
1d2fb970ebb8: Pull complete
3b145355f2d0: Pull complete
4c909b01ebfa: Pull complete
Digest: sha256:bec4d17339cbae2104071d1e6efaaf5eb384dd2e425af96b6e32965e24198b33
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/sdk:3.1-buster
 ---> e46b7d28a98a
Step 6/20 : WORKDIR /src
 ---> Running in 7a0e2b24b1ce
Removing intermediate container 7a0e2b24b1ce
 ---> e700dae37c16
Step 7/20 : COPY ["src/Services/Coupon/Coupon.API/Coupon.API.csproj", "src/Services/Coupon/Coupon.API/"]
 ---> fccd5dc4c9ed
Step 8/20 : COPY ["src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.csproj", "src/BuildingBlocks/EventBus/EventBusRabbitMQ/"]
 ---> b3e3405aa6fe
Step 9/20 : COPY ["src/BuildingBlocks/EventBus/EventBus/EventBus.csproj", "src/BuildingBlocks/EventBus/EventBus/"]
 ---> 43722c886224
Step 10/20 : COPY ["src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.csproj", "src/BuildingBlocks/EventBus/EventBusServiceBus/"]
 ---> d7dd98aa3928
Step 11/20 : RUN dotnet restore "src/Services/Coupon/Coupon.API/Coupon.API.csproj"
 ---> Running in 4d255b3991ba
  Determining projects to restore...
  Restored /src/src/BuildingBlocks/EventBus/EventBus/EventBus.csproj (in 1.76 sec).
  Restored /src/src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.csproj (in 6.46 sec).
  Restored /src/src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.csproj (in 2.17 sec).
  Restored /src/src/Services/Coupon/Coupon.API/Coupon.API.csproj (in 7.14 sec).
Removing intermediate container 4d255b3991ba
 ---> 151e99e2c352
Step 12/20 : COPY . .
 ---> 37757d488bb8
Step 13/20 : WORKDIR "/src/src/Services/Coupon/Coupon.API"
 ---> Running in db3e895079c3
Removing intermediate container db3e895079c3
 ---> 2c15ecc1292b
Step 14/20 : RUN dotnet build "Coupon.API.csproj" -c Release -o /app/build
 ---> Running in d3ab546f8402
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /src/src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.csproj (in 703 ms).
  Restored /src/src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.csproj (in 18 ms).
  Restored /src/src/BuildingBlocks/EventBus/EventBus/EventBus.csproj (in 4 ms).
  Restored /src/src/Services/Coupon/Coupon.API/Coupon.API.csproj (in 869 ms).
  EventBus -> /app/build/EventBus.dll
  EventBusRabbitMQ -> /app/build/EventBusRabbitMQ.dll
  EventBusServiceBus -> /app/build/EventBusServiceBus.dll
  Coupon.API -> /app/build/Coupon.API.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:06.42
Removing intermediate container d3ab546f8402
 ---> 320e6f9a9366
Step 15/20 : FROM build AS publish
 ---> 320e6f9a9366
Step 16/20 : RUN dotnet publish "Coupon.API.csproj" -c Release -o /app/publish
 ---> Running in 487ecc66abd0
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  EventBus -> /src/src/BuildingBlocks/EventBus/EventBus/bin/Release/netstandard2.1/EventBus.dll
  EventBusRabbitMQ -> /src/src/BuildingBlocks/EventBus/EventBusRabbitMQ/bin/Release/netstandard2.1/EventBusRabbitMQ.dll
  EventBusServiceBus -> /src/src/BuildingBlocks/EventBus/EventBusServiceBus/bin/Release/netstandard2.1/EventBusServiceBus.dll
  Coupon.API -> /src/src/Services/Coupon/Coupon.API/bin/Release/netcoreapp3.1/Coupon.API.dll
  Coupon.API -> /app/publish/
Removing intermediate container 487ecc66abd0
 ---> 240ef610dbe0
Step 17/20 : FROM base AS final
 ---> f4c3d83145ed
Step 18/20 : WORKDIR /app
 ---> Running in 037d861c1f1a
Removing intermediate container 037d861c1f1a
 ---> 692f0443773b
Step 19/20 : COPY --from=publish /app/publish .
 ---> 859f4a3f0bc3
Step 20/20 : ENTRYPOINT ["dotnet", "Coupon.API.dll"]
 ---> Running in 1a20daf66451
Removing intermediate container 1a20daf66451
 ---> e9d2ad2661dc
Successfully built e9d2ad2661dc
Successfully tagged eshoplearn20211111192800181.azurecr.io/coupon.api:linux-latest
2021/11/13 16:58:38 Successfully executed container: build
2021/11/13 16:58:38 Executing step ID: push. Timeout(sec): 3600, Working directory: '', Network: ''
2021/11/13 16:58:38 Pushing image: eshoplearn20211111192800181.azurecr.io/coupon.api:linux-latest, attempt 1
The push refers to repository [eshoplearn20211111192800181.azurecr.io/coupon.api]
9edc509f48ec: Preparing
69577942a0be: Preparing
02b0ec2893bd: Preparing
b5225671be39: Preparing
bdab1eddaa68: Preparing
4f7ffb24cc12: Preparing
e81bff2725db: Preparing
4f7ffb24cc12: Waiting
e81bff2725db: Waiting
bdab1eddaa68: Layer already exists
02b0ec2893bd: Layer already exists
b5225671be39: Layer already exists
e81bff2725db: Layer already exists
4f7ffb24cc12: Layer already exists
69577942a0be: Pushed
9edc509f48ec: Pushed
linux-latest: digest: sha256:8e70b5ae930f41634b857c69a2470b8ba01a0deded503b160113fc99a18c7512 size: 1792
2021/11/13 16:58:42 Successfully pushed image: eshoplearn20211111192800181.azurecr.io/coupon.api:linux-latest
2021/11/13 16:58:42 Step ID: build marked as successful (elapsed time in seconds: 74.615584)
2021/11/13 16:58:42 Populating digests for step ID: build...
2021/11/13 16:58:44 Successfully populated digests for step ID: build
2021/11/13 16:58:44 Step ID: push marked as successful (elapsed time in seconds: 4.237458)
2021/11/13 16:58:44 The following dependencies were found:
2021/11/13 16:58:44
- image:
    registry: eshoplearn20211111192800181.azurecr.io
    repository: coupon.api
    tag: linux-latest
    digest: sha256:8e70b5ae930f41634b857c69a2470b8ba01a0deded503b160113fc99a18c7512
  runtime-dependency:
    registry: mcr.microsoft.com
    repository: dotnet/core/aspnet
    tag: 3.1-buster-slim
    digest: sha256:f093d820b4bcfab7847e6c469104930f432a7dbc09265f6a987089b2d3a21009
  buildtime-dependency:
  - registry: mcr.microsoft.com
    repository: dotnet/core/sdk
    tag: 3.1-buster
    digest: sha256:bec4d17339cbae2104071d1e6efaaf5eb384dd2e425af96b6e32965e24198b33
  git: {}

Run ID: cf3 was successful after 1m25s

Building image "webspa"...
> az acr build --registry eshoplearn20211111192800181 --image eshoplearn20211111192800181.azurecr.io/webspa:linux-latest --file src/Web/WebSPA/Dockerfile.acr .
Packing source code into tar to upload...
Excluding '.gitignore' based on default ignore rules
Uploading archived source code from '/tmp/build_archive_bbb16bdb7d5f44d8a38e9be880e71881.tar.gz'...
Sending context (7.400 MiB) to registry: eshoplearn20211111192800181...
Queued a build with ID: cf4
Waiting for an agent...
2021/11/13 16:59:26 Downloading source code...
2021/11/13 16:59:27 Finished downloading source code
2021/11/13 16:59:27 Using acb_vol_530572f2-f9c3-4e82-b5c3-3fd56130df95 as the home volume
2021/11/13 16:59:27 Setting up Docker configuration...
2021/11/13 16:59:28 Successfully set up Docker configuration
2021/11/13 16:59:28 Logging in to registry: eshoplearn20211111192800181.azurecr.io
2021/11/13 16:59:29 Successfully logged into eshoplearn20211111192800181.azurecr.io
2021/11/13 16:59:29 Executing step ID: build. Timeout(sec): 28800, Working directory: '', Network: ''
2021/11/13 16:59:29 Scanning for dependencies...
2021/11/13 16:59:30 Successfully scanned dependencies
2021/11/13 16:59:30 Launching container with name: build
Sending build context to Docker daemon  15.86MB
Step 1/23 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
3.1-buster-slim: Pulling from dotnet/core/aspnet
b380bbd43752: Pulling fs layer
e4f4d095d04a: Pulling fs layer
bac3a3896817: Pulling fs layer
4dd004cdf57c: Pulling fs layer
561aa5f288e6: Pulling fs layer
4dd004cdf57c: Waiting
561aa5f288e6: Waiting
bac3a3896817: Verifying Checksum
bac3a3896817: Download complete
b380bbd43752: Verifying Checksum
b380bbd43752: Download complete
4dd004cdf57c: Verifying Checksum
4dd004cdf57c: Download complete
e4f4d095d04a: Verifying Checksum
e4f4d095d04a: Download complete
561aa5f288e6: Verifying Checksum
561aa5f288e6: Download complete
b380bbd43752: Pull complete
e4f4d095d04a: Pull complete
bac3a3896817: Pull complete
4dd004cdf57c: Pull complete
561aa5f288e6: Pull complete
Digest: sha256:f093d820b4bcfab7847e6c469104930f432a7dbc09265f6a987089b2d3a21009
Status: Downloaded newer image for mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
 ---> 0bcae74bb1e8
Step 2/23 : WORKDIR /app
 ---> Running in 1b8324ebb641
Removing intermediate container 1b8324ebb641
 ---> 228ec2bb2685
Step 3/23 : EXPOSE 80
 ---> Running in 48c8ea01e5ff
Removing intermediate container 48c8ea01e5ff
 ---> c7d5786aa22e
Step 4/23 : FROM node as node-build
latest: Pulling from library/node
bb7d5a84853b: Pulling fs layer
f02b617c6a8c: Pulling fs layer
d32e17419b7e: Pulling fs layer
c9d2d81226a4: Pulling fs layer
3c24ae8b6604: Pulling fs layer
a7c459a8e2ce: Pulling fs layer
6907b68f1eec: Pulling fs layer
67ca14c3c53c: Pulling fs layer
7e250bc43b70: Pulling fs layer
c9d2d81226a4: Waiting
3c24ae8b6604: Waiting
a7c459a8e2ce: Waiting
6907b68f1eec: Waiting
67ca14c3c53c: Waiting
7e250bc43b70: Waiting
f02b617c6a8c: Verifying Checksum
f02b617c6a8c: Download complete
d32e17419b7e: Verifying Checksum
d32e17419b7e: Download complete
bb7d5a84853b: Verifying Checksum
bb7d5a84853b: Download complete
a7c459a8e2ce: Verifying Checksum
a7c459a8e2ce: Download complete
c9d2d81226a4: Verifying Checksum
c9d2d81226a4: Download complete
67ca14c3c53c: Verifying Checksum
67ca14c3c53c: Download complete
7e250bc43b70: Verifying Checksum
7e250bc43b70: Download complete
6907b68f1eec: Verifying Checksum
6907b68f1eec: Download complete
3c24ae8b6604: Verifying Checksum
3c24ae8b6604: Download complete
bb7d5a84853b: Pull complete
f02b617c6a8c: Pull complete
d32e17419b7e: Pull complete
c9d2d81226a4: Pull complete
3c24ae8b6604: Pull complete
a7c459a8e2ce: Pull complete
6907b68f1eec: Pull complete
67ca14c3c53c: Pull complete
7e250bc43b70: Pull complete
Digest: sha256:fb256ef025424b407fb806a9828b105d82aac93c7168a1a8bc156bc82996b939
Status: Downloaded newer image for node:latest
 ---> 803ad17a604b
Step 5/23 : WORKDIR /web/src
 ---> Running in 4a8cd056ad8f
Removing intermediate container 4a8cd056ad8f
 ---> faf5a2c4af52
Step 6/23 : COPY src/Web/WebSPA/Client/package.json .
 ---> ebb55fa91593
Step 7/23 : COPY src/Web/WebSPA/Client/package-lock.json .
 ---> 6827b10f487e
Step 8/23 : RUN npm install
 ---> Running in 2ae18e1772ee
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile

npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.0: this library is no longer supported
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated chokidar@2.1.6: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated @types/protractor@4.0.0: This is a stub types definition for Protractor (https://github.com/angular/protractor). Protractor provides its own type definitions, so you don't need @types/protractor installed!
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated buffer@4.9.1: This version of 'buffer' is out-of-date. You must update to v4.9.2 or newer
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated highlight.js@9.15.9: Version no longer supported. Upgrade to @latest
npm WARN deprecated core-js@2.6.5: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@3.2.1: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 1562 packages, and audited 1563 packages in 1m

24 packages are looking for funding
  run `npm fund` for details

71 vulnerabilities (2 low, 29 moderate, 38 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm notice
npm notice New patch version of npm available! 8.1.2 -> 8.1.3
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.1.3>
npm notice Run `npm install -g npm@8.1.3` to update!
npm notice

Removing intermediate container 2ae18e1772ee
 ---> 72dfe8908e97
Step 9/23 : COPY src/Web/WebSPA/Client .
 ---> 8aa465a8a2df
Step 10/23 : RUN npm run build:prod
 ---> Running in 52ad70468be7

> eshopaspnetnetcoredockerspa@0.0.0 build:prod
> ng build --prod --aot --extract-css

(node:19) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/web/src/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/web/src/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/web/src/node_modules/webpack/lib/NormalModule.js:449:10)
    at /web/src/node_modules/webpack/lib/NormalModule.js:481:5
    at /web/src/node_modules/webpack/lib/NormalModule.js:342:12
    at /web/src/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at iterateNormalLoaders (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /web/src/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at runSyncOrAsync (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at iterateNormalLoaders (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /web/src/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at context.callback (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /web/src/node_modules/postcss-loader/src/index.js:197:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/web/src/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/web/src/node_modules/webpack/lib/NormalModule.js:401:16)
    at /web/src/node_modules/webpack/lib/NormalModule.js:433:10
    at /web/src/node_modules/webpack/lib/NormalModule.js:308:13
    at /web/src/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /web/src/node_modules/loader-runner/lib/LoaderRunner.js:200:19
    at VirtualFileSystemDecorator.readFile (/web/src/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:46:13)
    at processResource (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:199:11)
    at iteratePitchingLoaders (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at iteratePitchingLoaders (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /web/src/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/web/src/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/web/src/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/web/src/node_modules/webpack/lib/NormalModule.js:280:3)
    at NormalModule.build (/web/src/node_modules/webpack/lib/NormalModule.js:427:15)
    at Compilation.buildModule (/web/src/node_modules/webpack/lib/Compilation.js:635:10)
    at /web/src/node_modules/webpack/lib/Compilation.js:884:14
    at /web/src/node_modules/webpack/lib/NormalModuleFactory.js:405:6
    at /web/src/node_modules/webpack/lib/NormalModuleFactory.js:155:13
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/web/src/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at /web/src/node_modules/webpack/lib/NormalModuleFactory.js:138:29
    at /web/src/node_modules/webpack/lib/NormalModuleFactory.js:342:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
The command '/bin/sh -c npm run build:prod' returned a non-zero code: 1
2021/11/13 17:01:53 Container failed during run: build. No retries remaining.
failed to run step ID: build: exit status 1

Run ID: cf4 failed after 2m27s. Error: failed during run, err: exit status 1
Run failed

Error building WebSPA!

```

**Comment by nishanil** [comment]
Thanks @ruchinmunjal for reporting this. We have provided an interim fix in the MS Learn repo. Please try again and let us know if you can move forward in the module.

cc @sughosneo

**Comment by ruchinmunjal** [comment]
Thank you. I couldn't get to it earlier but can confirm , this works now.
