### ISSUE TITLE
System.ArgumentException "The Path must be absolute" WebMVC and WebSPA

### ISSUE THREAD

**Issue by ppathak** [dotnet/eShopOnContainers#1802]
Desktop Docker 4.3.0
VS 2022
Windows 10.
WSL2 (Ubuntu-20.04)

System.ArgumentException: The path must be absolute. (Parameter 'root')

   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)

   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)

   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__1_0(String contentRoot)

   at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)

   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)

   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)

   at Microsoft.AspNetCore.WebHost.<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)

   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)

   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()

   at Program.<<Main>$>g__BuildWebHost|0_0(IConfiguration configuration, String[] args) in C:\PrashantStudies\eShopOnContainers\src\Web\WebMVC\Program.cs:line 26

   at Program.<Main>$(String[] args) in C:\PrashantStudies\eShopOnContainers\src\Web\WebMVC\Program.cs:line 8

**Comment by josephwambura** [comment]
[19:22:23 FTL] Program terminated unexpectedly (WebStatus)!
System.ArgumentException: The path must be absolute. (Parameter 'root')
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__1_0(String contentRoot)
   at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
   at Microsoft.AspNetCore.WebHost.<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Program.<<Main>$>g__BuildWebHost|0_0(IConfiguration configuration, String[] args) in C:\BlahBlah\eShopOnContainers\src\Web\WebStatus\Program.cs:line 28
   at Program.<Main>$(String[] args) in C:\BlahBlah\eShopOnContainers\src\Web\WebStatus\Program.cs:line 8

**Comment by Eduardo-Guedes** [comment]
Put on IdentityAPI file appsettings.json:

  "ConnectionString": "Server=tcp:127.0.0.1,5433;Initial Catalog=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word",

**Comment by erjain** [comment]
WebSPA has the issue but WebMVC is running fine, you can give it some time after running the application, or you can follow the instructions as per https://github.com/dotnet-architecture/eShopOnContainers#getting-started.

**Comment by addinfinity** [comment]
Facing same issue. Trying hard to understand whats wrong. Following apps/apis are failing

|App|Error|
|---|---|
|IdentityApi|System.ArgumentException: The path must be absolute. (Parameter 'root')|
|WebMVC|System.ArgumentException: The path must be absolute. (Parameter 'root')|
|WebSPA|[12:57:22 ERR] ERROR in GetPreconfiguredImages: Value cannot be null. (Parameter 'path1')[13:02:52 ERR] Connection id "0HMFDBR7T4K5S", Request id "0HMFDBR7T4K5S:00000002": An unhandled exception was thrown by the application.System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.|

**Comment by erjain** [comment]
Many times whenever there will be a failure while starting the application it may corrupt the DB entries. Can you test with deleting all docker images and volumes or reset Docker and try again? Also, wait for the WebStatus project to show all the services healthy, before navigating to the Web Clients.  
To run WebSPA with Visual Studio in debug mode, you can follow the steps recently updated in [wiki](https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup#optional---to-run-webspa-project-via-visual-studio-2022-in-debug-mode). Let us know if this works for you.

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
