### ISSUE TITLE
Deploying to AKS - Unhandled Exception on webMVC app

### ISSUE THREAD

**Issue by jpocloud** [dotnet/eShopOnContainers#1831]
I'm following instructions on: https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS).

The only difference I did was use the deploy-all.sh script in the Helm folder instead of the deploy-all.ps1 powershell script. The sh script existed in the repo but was not referenced in the deploy instructions. I am running this from linux. Note that I also used public images and did not do any rebuild.

After deploying successfully... the webmvc, mobileshoppingagg, and webshoppingagg are in CrashLoopBackOff. The rest of the apps seems to be fine and in running state. The lines mentioned below did not relate to the current source code.

Here is the Error:
~/eShopOnContainers/deploy/k8s/helm$ kubectl logs -n eshop eshop-webmvc-68b445b8fb-99zfl
[14:38:45 INF] Configuring web host (eShopOnContainers.WebMVC)...
[14:38:45 FTL] Program terminated unexpectedly (eShopOnContainers.WebMVC)!
System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at Microsoft.eShopOnContainers.WebMVC.ServiceCollectionExtensions.AddHealthChecks(IServiceCollection services, IConfiguration configuration) in /src/src/Web/WebMVC/Startup.cs:line 138
   at Microsoft.eShopOnContainers.WebMVC.Startup.ConfigureServices(IServiceCollection services) in /src/src/Web/WebMVC/Startup.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.eShopOnContainers.WebMVC.Program.Main(String[] args) in /src/src/Web/WebMVC/Program.cs:line 24

**Comment by erjain** [comment]
Hi @jpocloud,  Due to bandwidth constraints we are unable to check deployment with deploy-all.sh script file, right now we are deploying on Kubernetes using deploy-all.ps1. However, if anyone in the community wants to work on this, we are happy to review and accept a PR from the community on this.
