### ISSUE TITLE
Name or service not known - Ordering HTTP Background Check

### ISSUE THREAD

**Issue by ccalvarez** [dotnet/eShopOnContainers#1901]
Hi.

I got all the services running except for "Ordering HTTP Background Check", where I receive this error:

![image](https://user-images.githubusercontent.com/2665104/164533112-fff069fc-417d-4bb1-aeba-445db4cbed0e.png)

In the logs of the `eshop/ordering.backgroundtasks:linux-latest` container I see this message:

_RabbitMQ Client could not connect_

`{"EventId":0,"LogLevel":"Information","Category":"Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ.DefaultRabbitMQPersistentConnection","Message":"RabbitMQ Client is trying to connect","State":{"Message":"RabbitMQ Client is trying to connect","{OriginalFormat}":"RabbitMQ Client is trying to connect"}}
[18:30:09 INF] RabbitMQ Client is trying to connect
{"EventId":0,"LogLevel":"Warning","Category":"Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ.DefaultRabbitMQPersistentConnection","Message":"RabbitMQ Client could not connect after 2.0s (None of the specified endpoints were reachable)","Exception":"RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable  ---\u003E System.AggregateException: One or more errors occurred. (Connection failed)  ---\u003E RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed  ---\u003E System.Net.Sockets.SocketException (111): Connection refused    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)    at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.\u003C\u003Ec.\u003C.cctor\u003Eb__4_0(Object state) --- End of stack trace from previous location ---    at RabbitMQ.Client.Impl.TcpClientAdapter.ConnectAsync(String host, Int32 port)    at RabbitMQ.Client.Impl.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout)    at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)    --- End of inner exception stack trace ---    at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)    at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingAddressFamily(AmqpTcpEndpoint endpoint, Func\u00602 socketFactory, TimeSpan timeout, AddressFamily family)    at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingIPv4(AmqpTcpEndpoint endpoint, Func\u00602 socketFactory, TimeSpan timeout)    at RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func\u00602 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)    at RabbitMQ.Client.Framing.Impl.IProtocolExtensions.CreateFrameHandler(IProtocol protocol, AmqpTcpEndpoint endpoint, Func\u00602 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)    at RabbitMQ.Client.ConnectionFactory.CreateFrameHandler(AmqpTcpEndpoint endpoint)    at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func\u00602 selector)    --- End of inner exception stack trace ---    at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func\u00602 selector)    at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)    at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)    --- End of inner exception stack trace ---    at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)    at RabbitMQ.Client.ConnectionFactory.CreateConnection(String clientProvidedName)    at RabbitMQ.Client.ConnectionFactory.CreateConnection()    at Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ.DefaultRabbitMQPersistentConnection.\u003CTryConnect\u003Eb__11_2() in /src/BuildingBlocks/EventBus/EventBusRabbitMQ/DefaultRabbitMQPersistentConnection.cs:line 74    at Polly.Policy.\u003C\u003Ec__DisplayClass108_0.\u003CExecute\u003Eb__0(Context ctx, CancellationToken ct)    at Polly.Policy.\u003C\u003Ec__DisplayClass138_0.\u003CImplementation\u003Eb__0(Context ctx, CancellationToken token)    at Polly.Retry.RetryEngine.Implementation[TResult](Func\u00603 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates\u00601 shouldRetryResultPredicates, Action\u00604 onRetry, Int32 permittedRetryCount, IEnumerable\u00601 sleepDurationsEnumerable, Func\u00604 sleepDurationProvider)","State":{"Message":"RabbitMQ Client could not connect after 2.0s (None of the specified endpoints were reachable)","TimeOut":"2.0","ExceptionMessage":"None of the specified endpoints were reachable","{OriginalFormat}":"RabbitMQ Client could not connect after {TimeOut}s ({ExceptionMessage})"}}
[18:30:14 WRN] RabbitMQ Client could not connect after 2.0s (None of the specified endpoints were reachable)
RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable
 ---> System.AggregateException: One or more errors occurred. (Connection failed)
 ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at RabbitMQ.Client.Impl.TcpClientAdapter.ConnectAsync(String host, Int32 port)
   at RabbitMQ.Client.Impl.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingAddressFamily(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout, AddressFamily family)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingIPv4(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout)
   at RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)
   at RabbitMQ.Client.Framing.Impl.IProtocolExtensions.CreateFrameHandler(IProtocol protocol, AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)
   at RabbitMQ.Client.ConnectionFactory.CreateFrameHandler(AmqpTcpEndpoint endpoint)
   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IEndpointResolver endpoints)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   --- End of inner exception stack trace ---
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(String clientProvidedName)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection()
   at Microsoft.eShopOnContainers.BuildingBlocks.EventBusRabbitMQ.DefaultRabbitMQPersistentConnection.<TryConnect>b__11_2() in /src/BuildingBlocks/EventBus/EventBusRabbitMQ/DefaultRabbitMQPersistentConnection.cs:line 74
   at Polly.Policy.<>c__DisplayClass108_0.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass138_0.<Implementation>b__0(Context ctx, CancellationToken token)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)`

I used the RabbitMQ UI at http://localhost:15672/ and it's responding though:

![image](https://user-images.githubusercontent.com/2665104/164534224-13de64c8-4bb7-4782-9fc8-b4a5e42a5825.png)

I appreciate your help.

By the way, where can I see the credentials, i.e., 'sa' password, RabbitMQ user and password, etc.?

**Comment by ccalvarez** [comment]
I reran the `docker compose up` command, and all the services started.

Thanks.
