### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by quantrpeter** [dotnet/eShopOnContainers#1965]
Hi, i am in mac:

```
/Users/peter/workspace/eShopOnContainers/src>docker-compose --version
docker-compose version 1.29.2, build 5becea4c
```

```
/Users/peter/workspace/eShopOnContainers/src>docker-compose build
WARNING: The INSTRUMENTATION_KEY variable is not set. Defaulting to a blank string.
WARNING: The ORCHESTRATOR_TYPE variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_SERVICE_BUS_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_SERVICE_BUS_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_CATALOG_NAME variable is not set. Defaulting to a blank string.
WARNING: The ESHOP_AZURE_STORAGE_CATALOG_KEY variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 726, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

thanks

**Comment by erjain** [comment]
Hi @quantrpeter, thanks for posting here. There is an [issue](https://github.com/dotnet-architecture/eShopOnContainers/issues/1771) already reported on M1 Mac, which was resolved, sharing link which you can refer to: https://github.com/dotnet-architecture/eShopOnContainers/issues/1771.
Also please ensure to enable `docker.for.mac.localhost` hostname for the docker in the following file. 

https://github.com/dotnet-architecture/eShopOnContainers/blob/46219957ef763305030a0924d039fe4a25831b06/src/.env#L12

- To run the app 
- Go to the `/src/` directory

```text
docker-compose up sqldata
```
Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal window.

```text
docker-compose up
```
 Hope this helps.

**Comment by quantrpeter** [comment]
thanks, i just delete everything, clone the repo again, it back to work, thanks
