### ISSUE TITLE
Response status code does not indicate success

### ISSUE THREAD

**Issue by timyan56** [dotnet/eShopOnContainers#1977]
After docker-compose up command, it gives me this 500 error.
`HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).`

System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.eShopOnContainers.WebMVC.Services.CatalogService.GetCatalogItems(Int32 page, Int32 take, Nullable`1 brand, Nullable`1 type) in /src/Web/WebMVC/Services/CatalogService.cs:line 24
   at Microsoft.eShopOnContainers.WebMVC.Controllers.CatalogController.Index(Nullable`1 BrandFilterApplied, Nullable`1 TypesFilterApplied, Nullable`1 page, String errorMsg) in /src/Web/WebMVC/Controllers/CatalogController.cs:line 13
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   
<img width="1466" alt="Screenshot 2022-09-20 at 5 22 38 PM" src="https://user-images.githubusercontent.com/97575806/191221846-217edfde-f59f-4be1-8018-2986aee1b505.png">
<img width="1459" alt="Screenshot 2022-09-20 at 5 31 30 PM" src="https://user-images.githubusercontent.com/97575806/191222759-7d0caa2b-da60-4551-9567-2c82cb60f361.png">

I have no idea of what goes wrong.

**Comment by erjain** [comment]
HI @timyan56, thanks for posting your query. Sometimes an error during startup can disturb the application deployment and entries in the databases.  Could you please clean up old docker images and build the docker images again?  - To build and run the app 
- Go to the `/src/` directory and first-time build without cache

```text
docker-compose build --no-cache
```
- then, run

```text
docker-compose up sqldata
```
- Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal window.

```text
docker-compose up
```

Let us know if this works for you.

**Comment by timyan56** [comment]
Hi @erjain , thank you for the reply! I have just tried your solution, but the problem persists with the same error.
![Screenshot 2022-09-21 at 10 05 25 AM](https://user-images.githubusercontent.com/97575806/191397987-5fb94773-3150-4e66-8a89-901098e6f146.png)

**Comment by erjain** [comment]
Hi @timyan56, there seems to be an issue with the database, it's showing SqlCLient.SqlException, please ensure your SQL server image is up.

**Comment by timyan56** [comment]
Hi @erjain  I think the problem is caused by mssql not supporting arm architecture as the issue already mentioned  [here](https://github.com/microsoft/mssql-docker/issues/668)

**Comment by erjain** [comment]
If you are running on Mac, there is an [issue](https://github.com/dotnet-architecture/eShopOnContainers/issues/1771) already reported on M1 Mac, which was resolved, sharing link which you can refer to: https://github.com/dotnet-architecture/eShopOnContainers/issues/1771.
Also please ensure to enable `docker.for.mac.localhost` hostname for the docker in the following file. 

https://github.com/dotnet-architecture/eShopOnContainers/blob/46219957ef763305030a0924d039fe4a25831b06/src/.env#L12. Hope it helps.

**Comment by timyan56** [comment]
Hi @erjain  thank you for the [guidance](https://github.com/dotnet-architecture/eShopOnContainers/issues/1771). It works for me
