### ISSUE TITLE
Bug: Deployment on AKS - WebShoppingAgg don't start

### ISSUE THREAD

**Issue by kbeaugrand** [dotnet/eShopOnContainers#1981]
Hello, 

After deploying following the documented procedure using only the templates provided (with image `linux-latest`). The pod eshop-webshoppingagg does not start, and presents the following message: 

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at Microsoft.eShopOnContainers.Web.Shopping.HttpAggregator.Startup.ConfigureServices(IServiceCollection services) in /src/src/ApiGateways/Web.Bff.Shopping/aggregator/Startup.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.eShopOnContainers.Web.Shopping.HttpAggregator.Program.Main(String[] args) in /src/src/ApiGateways/Web.Bff.Shopping/aggregator/Program.cs:line 18
```

Could you help me to get this sample working ? 
I need to run that on AKS to present a demonstration of running such kind of distributed services with ServiceMesh....

Remarks, I can have this working on my PC using docker-compose, but that's clearly not what I need ;)

Regards

**Comment by erjain** [comment]
Hi @kbeaugrand, thanks for posting here. Have you tried deploying public images as per link https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS)#deploy-public-images-from-dockerhub
and then ensure to allow large headers: https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS)#allow-large-headers-needed-for-login-to-work. 
Let me know if this works.

**Comment by kbeaugrand** [comment]
Hi @erjain , 

I found the issue. I was not compiling the dev branch, so I think I was confronted to unexpected errors on this branch.
However, I found another issue regarding the SPA.

I'll open the corresponding issue in a few minutes.

Regards,
