### ISSUE TITLE
Exception on frontend web services

### ISSUE THREAD

**Issue by pavanmaz** [dotnet/eShopOnContainers#2013]
Hello All,

I am Pavan and i am trying to deploy the Eshoponcontainers on one of our AKS clusters. We are having issue with web tier of this application and pods are not starting, when i go and see on   pod logs i found following below exceptions and please help me what i am missing here. Only web is failing and all APIs and other Infra pods are running seamlessly. Requesting anyone faced this exception please help me out.

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at Microsoft.eShopOnContainers.Web.Shopping.HttpAggregator.Startup.ConfigureServices(IServiceCollection services) in /src/src/ApiGateways/Web.Bff.Shopping/aggregator/Startup.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.eShopOnContainers.Web.Shopping.HttpAggregator.Program.Main(String[] args) in /src/src/ApiGateways/Web.Bff.Shopping/aggregator/Program.cs:line 18
   

-----------------------------------------------------------------------------------------------------------------------------------------------

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: uriString
   at System.Uri..ctor(String uriString)
   at Microsoft.eShopOnContainers.Mobile.Shopping.HttpAggregator.Startup.ConfigureServices(IServiceCollection services) in /src/src/ApiGateways/Mobile.Bff.Shopping/aggregator/Startup.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.eShopOnContainers.Mobile.Shopping.HttpAggregator.Program.Main(String[] args) in /src/src/ApiGateways/Mobile.Bff.Shopping/aggregator/Program.cs:line 18

**Comment by erjain** [comment]
Hi @pavanmaz, thanks for sharing your query. Please go through this issue comment: https://github.com/dotnet-architecture/eShopOnContainers/issues/1981#issuecomment-1257815995. Let me know if this helps.

**Comment by erjain** [comment]
I am closing this issue, however, please feel free to reopen the issue in case of any more queries.
