### ISSUE TITLE
Quering `IntegrationEventLogs` throws Execution Timeout Expired on the sql server

### ISSUE THREAD

**Issue by makhele** [dotnet/eShopOnContainers#2030]
When I have > 6000 IntergrationEnventLogs records in the database and I hit the this [line](https://github.com/dotnet-architecture/eShopOnContainers/blob/4596d7aa99f841206e486e910d20b525cd48daf2/src/BuildingBlocks/EventBus/IntegrationEventLogEF/Services/IntegrationEventLogService.cs#L28):

```
var result = await _integrationEventLogContext.IntegrationEventLogs
            .Where(e => e.TransactionId == tid && e.State == EventStateEnum.NotPublished).ToListAsync();
```
 as part of the normal execution.

I get the following error and stacktrace:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.

 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.

   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__208_0(Task`1 result)

   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location ---

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

--- End of stack trace from previous location ---

   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)

   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)

   at IFMS.GMT.BuildingBlocks.IntegrationEventLogEF.Services.IntegrationEventLogService.RetrieveEventLogsPendingToPublishAsync(Guid transactionId) in D:\repos\IntegratedFleetManagementSystem.GMT\src\BuildingBlocks\BuildingBlocks.IntegrationEventLogEF\Services\IntegrationEventLogService.cs:line 38

   at IFMS.GMT.Services.VehicleManagement.WebAPI.Application.IntegrationEvents.VehicleManagementIntegrationEventService.PublishEventsThroughEventBusAsync(Guid transactionId) in D:\repos\IntegratedFleetManagementSystem.GMT\src\Services\VehicleManagement\VehicleManagement.WebAPI\Application\IntegrationEvents\VehicleManagementIntegrationEventService.cs:line 38

   at IFMS.GMT.Services.VehicleManagement.WebAPI.Application.Behaviors.TransactionBehaviour`2.<>c__DisplayClass4_0.<<Handle>b__0>d.MoveNext() in D:\repos\IntegratedFleetManagementSystem.GMT\src\Services\VehicleManagement\VehicleManagement.WebAPI\Application\Behaviors\TransactionBehaviour.cs:line 61

--- End of stack trace from previous location ---

```

Is this query slow? (if so are there any recommendations on how to improve it) because I tries to create and Index for `TransactionId` but still no changes

or my machaine together with sql server instance its running

**Comment by erjain** [comment]
Hi @makhele, thank you so much for posting your query here. You can increase the execution timeout, actually, timeout error depends on many factors, which we didn't emphasize here. You can increase the timeout in Program.cs or you can set it through your context. Please feel free to continue the conversation in case of more queries. I hope it helps.

**Comment by erjain** [comment]
I am closing this issue, however, feel free to continue the conversation or reopen it in case of more queries.
