### ISSUE TITLE
sqldata-1 docker 

### ISSUE THREAD

**Issue by Neilsons** [dotnet/eShopOnContainers#2033]
After checking out the current dev branch, after executing docker-compose build and docker-compose up, accessing http://host.docker.internal:5100/ is a lot unhealthy and reports an error as：“Cannot open database "Microsoft.eShopOnContainers.Service.IdentityDb" requested by the login. The login failed. Login failed for user 'sa'.”
Then I found that when I opened the sqldata-1 log, it kept reporting"Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'Microsoft.eShopOnContainers.Services.OrderingDb'. [CLIENT: 172.20.0.14]" . The following is the logging of the container after it has been started"SQL Server 2019 will run as non-root by default.
This container is running as user mssql.
Your master database file is owned by mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
2023-01-12 07:39:33.74 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_replicatedmaster.mdf' to '/var/opt/mssql/data/model_replicatedmaster.mdf'.
2023-01-12 07:39:33.78 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_replicatedmaster.ldf' to '/var/opt/mssql/data/model_replicatedmaster.ldf'.
2023-01-12 07:39:33.80 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_msdbdata.mdf' to '/var/opt/mssql/data/model_msdbdata.mdf'.
2023-01-12 07:39:33.84 Server      Setup step is FORCE copying system data file 'C:\templatedata\model_msdblog.ldf' to '/var/opt/mssql/data/model_msdblog.ldf'.
2023-01-12 07:39:33.91 Server      Microsoft SQL Server 2019 (RTM-CU18) (KB5017593) - 15.0.4261.1 (X64) 
        Sep 12 2022 15:07:06 
        Copyright (C) 2019 Microsoft Corporation
        Developer Edition (64-bit) on Linux (Ubuntu 20.04.5 LTS) <X64>
2023-01-12 07:39:33.91 Server      UTC adjustment: 0:00
2023-01-12 07:39:33.92 Server      (c) Microsoft Corporation.
2023-01-12 07:39:33.92 Server      All rights reserved.
2023-01-12 07:39:33.92 Server      Server process ID is 380.
2023-01-12 07:39:33.92 Server      Logging SQL Server messages in file '/var/opt/mssql/log/errorlog'.
2023-01-12 07:39:33.92 Server      Registry startup parameters: 
         -d /var/opt/mssql/data/master.mdf
         -l /var/opt/mssql/data/mastlog.ldf
         -e /var/opt/mssql/log/errorlog
2023-01-12 07:39:33.93 Server      SQL Server detected 1 sockets with 6 cores per socket and 12 logical processors per socket, 12 total logical processors; using 12 logical processors based on SQL Server licensing. This is an informational message; no user action is required.
2023-01-12 07:39:33.93 Server      SQL Server is starting at normal priority base (=7). This is an informational message only. No user action is required.
2023-01-12 07:39:33.93 Server      Detected 10065 MB of RAM. This is an informational message; no user action is required.
2023-01-12 07:39:33.94 Server      Using conventional memory in the memory manager.
2023-01-12 07:39:38.16 Server      Page exclusion bitmap is enabled.
2023-01-12 07:39:40.07 Server      Buffer pool extension is not supported on Linux platform.
2023-01-12 07:39:40.07 Server      Buffer Pool: Allocating 2097152 bytes for 1278900 hashPages.
2023-01-12 07:39:41.84 Server      Buffer pool extension is already disabled. No action is necessary.
2023-01-12 07:39:43.66 Server      Successfully initialized the TLS configuration. Allowed TLS protocol versions are ['1.0 1.1 1.2']. Allowed TLS ciphers are ['ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!DHE-RSA-AES256-GCM-SHA384:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES256-SHA:!DHE-RSA-AES128-SHA'].
2023-01-12 07:39:44.24 Server      Query Store settings initialized with enabled = 1, 
2023-01-12 07:39:44.38 Server      The maximum number of dedicated administrator connections for this instance is '1'
2023-01-12 07:39:45.08 Server      Node configuration: node 0: CPU mask: 0x0000000000000fff:0 Active CPU mask: 0x0000000000000fff:0. This message provides a description of the NUMA configuration for this computer. This is an informational message only. No user action is required.
2023-01-12 07:39:51.82 Server      Using dynamic lock allocation.  Initial allocation of 2500 Lock blocks and 5000 Lock Owner blocks per node.  This is an informational message only.  No user action is required.
2023-01-12 07:39:52.29 Server      In-Memory OLTP initialized on lowend machine.
2023-01-12 07:39:54.23 Server      [INFO] Created Extended Events session 'hkenginexesession'
2023-01-12 07:39:54.23 Server      Database Instant File Initialization: enabled. For security and performance considerations see the topic 'Database Instant File Initialization' in SQL Server Books Online. This is an informational message only. No user action is required.
ForceFlush is enabled for this instance. 
2023-01-12 07:39:54.38 Server      Total Log Writer threads: 2. This is an informational message; no user action is required.
2023-01-12 07:39:54.39 Server      CLR version v4.0.30319 loaded.
2023-01-12 07:39:54.41 Server      clflushopt is selected for pmem flush operation.
2023-01-12 07:39:54.42 Server      Software Usage Metrics is disabled.
2023-01-12 07:40:05.92 spid9s      [1]. Feature Status: PVS: 0. CTR: 0. ConcurrentPFSUpdate: 1.
2023-01-12 07:40:06.67 spid9s      Starting up database 'master'.
ForceFlush feature is enabled for log durability.
2023-01-12 07:40:11.49 spid9s      Recovery completed for database master (database ID 1) in 4 second(s) (analysis 2945 ms, redo 200 ms, undo 176 ms [system undo 0 ms, regular undo 0 ms].) This is an informational message only. No user action is required.
2023-01-12 07:40:18.37 spid9s      Resource governor reconfiguration succeeded.
2023-01-12 07:40:18.37 spid9s      SQL Server Audit is starting the audits. This is an informational message. No user action is required.
2023-01-12 07:40:18.71 spid9s      SQL Server Audit has started the audits. This is an informational message. No user action is required.
2023-01-12 07:40:45.06 spid9s      SQL Trace ID 1 was started by login "sa".
2023-01-12 07:40:46.81 spid9s      Server name is 'e1aa9c6979bc'. This is an informational message only. No user action is required.
2023-01-12 07:40:56.84 spid49s     Always On: The availability replica manager is starting. This is an informational message only. No user action is required.
2023-01-12 07:40:56.84 spid49s     Always On: The availability replica manager is waiting for the instance of SQL Server to allow client connections. This is an informational message only. No user action is required.
2023-01-12 07:40:57.13 spid48s     A self-generated certificate was successfully loaded for encryption.
2023-01-12 07:40:59.07 spid48s     Server is listening on [ 'any' <ipv6> 1433].
2023-01-12 07:40:59.22 spid48s     Server is listening on [ 'any' <ipv4> 1433].
2023-01-12 07:40:59.42 spid9s      [4]. Feature Status: PVS: 0. CTR: 0. ConcurrentPFSUpdate: 1.
2023-01-12 07:40:59.63 Server      Server is listening on [ ::1 <ipv6> 1434].
2023-01-12 07:40:59.66 Server      Server is listening on [ 127.0.0.1 <ipv4> 1434].
2023-01-12 07:40:59.74 Server      Dedicated admin connection support was established for listening locally on port 1434.
2023-01-12 07:40:59.78 spid17s     [32767]. Feature Status: PVS: 0. CTR: 0. ConcurrentPFSUpdate: 1.
2023-01-12 07:41:00.35 spid9s      Starting up database 'msdb'.
2023-01-12 07:41:04.63 spid48s     Server is listening on [ ::1 <ipv6> 1431].
2023-01-12 07:41:04.73 spid48s     Server is listening on [ 127.0.0.1 <ipv4> 1431].
2023-01-12 07:41:05.03 spid48s     SQL Server is now ready for client connections. This is an informational message; no user action is required.
2023-01-12 07:41:05.22 spid17s     Starting up database 'mssqlsystemresource'.
2023-01-12 07:41:05.94 spid17s     The resource database build version is 15.00.4261. This is an informational message only. No user action is required.
2023-01-12 07:41:08.79 spid17s     Recovery completed for database mssqlsystemresource (database ID 32767) in 3 second(s) (analysis 1874 ms, redo 0 ms, undo 503 ms [system undo 0 ms, regular undo 0 ms].) This is an informational message only. No user action is required.
DBSTARTUP (mssqlsystemresource, 32767): FCBOpenTime took 205 ms
DBSTARTUP (mssqlsystemresource, 32767): FCBHeaderReadTime took 218 ms
DBSTARTUP (mssqlsystemresource, 32767): FileMgrPreRecoveryTime took 281 ms
DBSTARTUP (mssqlsystemresource, 32767): MasterFilesScanTime took 167 ms
DBSTARTUP (mssqlsystemresource, 32767): LogMgrPreRecoveryTime took 167 ms
DBSTARTUP (mssqlsystemresource, 32767): AnalysisRecTime took 1874 ms
DBSTARTUP (mssqlsystemresource, 32767): PhysicalRecoveryTime took 1874 ms
2023-01-12 07:41:09.16 spid17s     [3]. Feature Status: PVS: 0. CTR: 0. ConcurrentPFSUpdate: 1.
2023-01-12 07:41:09.19 spid17s     Starting up database 'model'.
2023-01-12 07:41:09.30 Logon       Error: 18456, Severity: 14, State: 38.
2023-01-12 07:41:09.30 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'Microsoft.eShopOnContainers.Services.OrderingDb'. [CLIENT: 172.20.0.15]
2023-01-12 07:41:10.53 spid9s      Recovery completed for database msdb (database ID 4) in 6 second(s) (analysis 4005 ms, redo 0 ms, undo 1247 ms [system undo 0 ms, regular undo 0 ms].) This is an informational message only. No user action is required.
2023-01-12 07:41:11.45 spid17s     Recovery completed for database model (database ID 3) in 2 second(s) (analysis 1582 ms, redo 0 ms, undo 176 ms [system undo 0 ms, regular undo 0 ms].) This is an informational message only. No user action is required.
2023-01-12 07:41:11.69 spid17s     Clearing tempdb database.
2023-01-12 07:41:12.56 Logon       Error: 18456, Severity: 14, State: 38.
2023-01-12 07:41:12.56 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'Microsoft.eShopOnContainers.Services.OrderingDb'. [CLIENT: 172.20.0.14]
2023-01-12 07:41:14.76 spid17s     [2]. Feature Status: PVS: 0. CTR: 0. ConcurrentPFSUpdate: 1.
2023-01-12 07:41:15.87 spid17s     Starting up database 'tempdb'.
DBSTARTUP (msdb, 4): FCBOpenTime took 582 ms
DBSTARTUP (msdb, 4): LogMgrPreRecoveryTime took 3404 ms
DBSTARTUP (msdb, 4): AnalysisRecTime took 4005 ms
DBSTARTUP (msdb, 4): PhysicalRecoveryTime took 4124 ms
DBSTARTUP (msdb, 4): RecoveryCompletionTime took 573 ms
DBSTARTUP (msdb, 4): StartupInDatabaseTime took 4662 ms
DBSTARTUP (msdb, 4): LinkSnapshotsTime took 502 ms
2023-01-12 07:41:19.56 Logon       Error: 18456, Severity: 14, State: 38.
2023-01-12 07:41:19.56 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'Microsoft.eShopOnContainers.Services.CatalogDb'. [CLIENT: 172.20.0.11]
2023-01-12 07:41:20.98 Logon       Error: 18456, Severity: 14, State: 38.
2023-01-12 07:41:20.98 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'Microsoft.eShopOnContainers.Service.IdentityDb'. [CLIENT: 172.20.0.13]
2023-01-12 07:41:21.35 spid17s     Recovery completed for database tempdb (database ID 2) in 3 second(s) (analysis 436 ms, redo 0 ms, undo 1886 ms [system undo 0 ms, regular undo 0 ms].) This is an informational message only. No user action is required.
2023-01-12 07:41:22.67 Server      Common language runtime (CLR) functionality initialized.
2023-01-12 07:41:22.90 Logon       Error: 18456, Severity: 14, State: 38.
2023-01-12 07:41:22.90 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'Microsoft.eShopOnContainers.Services.OrderingDb'. [CLIENT: 172.20.0.14]
2023-01-12 07:41:23.45 Logon       Error: 18456, Severity: 14, State: 38.
2023-01-12 07:41:23.45 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'Microsoft.eShopOnContainers.Services.OrderingDb'. [CLIENT: 172.20.0.14]
2023-01-12 07:41:23.65 spid17s     The tempdb database has 8 data file(s).
2023-01-12 07:41:23.80 spid19s     The Service Broker endpoint is in disabled or stopped state.
2023-01-12 07:41:23.80 spid19s     The Database Mirroring endpoint is in disabled or stopped state.
2023-01-12 07:41:23.95 spid9s      Recovery is complete. This is an informational message only. No user action is required.
2023-01-12 07:41:24.95 spid19s     Service Broker manager has started.
2023-01-12 07:41:35.52 Logon       Error: 18456, Severity: 14, State: 38."

**Comment by erjain** [comment]
Hi @Neilsons, thanks for sharing your query.  Could you please clean up the old docker images and build the docker images again?  - To build and run the app 
- Go to the `/src/` directory and first-time build without cache

```text
docker-compose build --no-cache
```
- then, run

```text
docker-compose up sqldata
```
- Once it's ready to accept the new connection, then you can bring up the other container by using the following command from a separate terminal window.

```text
docker-compose up
```

Let us know if this works for you.

**Comment by Neilsons** [comment]
It doesn't work well, the sqldata-1 container log reports the same errors as above

**Comment by erjain** [comment]
Hi @Neilsons, I have tested the application and it is working fine for me. Can you please check out this wiki page and follow the instructions: https://github.com/dotnet-architecture/eShopOnContainers/wiki/Windows-setup. I hope it helps. Thanks

**Comment by ragava28** [comment]
I am also facing same issue , but in my case, I am deploying it to AKS following the steps in https://github.com/dotnet-architecture/eShopOnContainers/wiki/Deploy-to-Azure-Kubernetes-Service-(AKS) using Helm Charts.

Error .

Identity Microservice is not able to connect to SQL container.

[04:14:42 ERR] Health check IdentityDB-check with status Unhealthy completed after 18.8849ms with message 'null'
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "IdentityDb" requested by the login. The login failed.
Login failed for user 'sa'.
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location ---
   at HealthChecks.SqlServer.SqlServerHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
ClientConnectionId:e6e58361-8dab-4f83-b164-f07184b76f7f
Error Number:4060,State:1,Class:11

**Comment by ragava28** [comment]
after redeploying the complete application, it started working. not sure what created the issue,

**Comment by erjain** [comment]
Sometimes a failed startup may corrupt the database entries, or it may take more time, it is better to wait for the WebStatus project to show all the services healthy.
Hi @Neilsons, are you able to resolve the issue?

**Comment by erjain** [comment]
Hi @Neilsons, are you still facing the issue?

**Comment by erjain** [comment]
I have tested the application and it is working fine, I am closing this issue, however, feel free to continue the conversation or reopen it if you are looking for more help.
